/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover the public API */
        get: operations["getDiscovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the complete biomedical Home snapshot
         * @description Returns the stored Home document from one immutable published generation.
         */
        get: operations["getBiomedicalHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accepted biomedical Journals
         * @description Uses the stable order `paper_count DESC, slug`.
         */
        get: operations["listBiomedicalJournals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one accepted biomedical Journal
         * @description `limit` and `cursor` paginate only the immutable
         *     `detail_payload.recent_papers.items` array.
         */
        get: operations["getBiomedicalJournal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List methods in the current generation */
        get: operations["listMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methods/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one visible method from the current generation */
        get: operations["getMethod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and filter papers in the current generation */
        get: operations["listPapers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one visible paper from the current generation
         * @description Malformed UUIDs, absent papers, and papers not visible in the published
         *     generation intentionally share the same 404 response.
         */
        get: operations["getPaper"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted research opportunity analysis */
        get: operations["listResearchOpportunities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get statistics from the current catalog generation */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accepted biomedical Subjects
         * @description Uses the stable order `paper_count DESC, slug`.
         */
        get: operations["listBiomedicalSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one accepted biomedical Subject
         * @description `limit` and `cursor` paginate only the immutable
         *     `detail_payload.recent_papers.items` array.
         */
        get: operations["getBiomedicalSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List topics in the current generation */
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one visible topic from the current generation */
        get: operations["getTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted method trend analysis */
        get: operations["listMethodTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted paper trend analysis */
        get: operations["listPaperTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted topic trend analysis */
        get: operations["listTopicTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API process health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalysisMetadata: {
            /** Format: uuid */
            analysis_run_id?: string;
            analysis_type?: string;
            baseline_window_days?: number;
            cohort_revision?: string;
            coverage_ratio: components["schemas"]["RatioCatalogValue"];
            formula_version?: components["schemas"]["StringCatalogValue"];
            generated_at: components["schemas"]["StringCatalogValue"];
            missing_signals: (string | components["schemas"]["MissingSignal"])[];
            recent_window_days?: number;
            sample_size: components["schemas"]["IntegerCatalogValue"];
            sources: components["schemas"]["StringArrayCatalogValue"];
            window_days: components["schemas"]["IntegerCatalogValue"];
        };
        AuthorReference: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            institution_id?: string;
            institution_name?: string;
            is_corresponding: boolean;
            name: string;
            orcid?: string;
            position: number;
        };
        BiomedicalEligibilityEvidence: {
            matches: components["schemas"]["BiomedicalEligibilitySubjectEvidence"][];
            metric_year: number;
            metrics: components["schemas"]["BiomedicalEligibilityMetricEvidence"][];
            policy_version: string;
            /** Format: uuid */
            subject_version_id: string;
            subject_version_key: string;
            venue: components["schemas"]["BiomedicalEligibilityVenueEvidence"];
        };
        BiomedicalEligibilityMetricEvidence: {
            jcr_category: string;
            metric_year: number;
            /** Format: uuid */
            venue_id: string;
            /** Format: uuid */
            venue_metric_snapshot_id: string;
        };
        BiomedicalEligibilityRevision: {
            /** Format: date-time */
            assessed_at: string;
            /** @constant */
            decision: "accepted";
            evidence: components["schemas"]["BiomedicalEligibilityEvidence"];
            /** Format: uuid */
            id: string;
            metric_year: number;
            policy_version: string;
            /** Format: uuid */
            subject_version_id: string;
            subject_version_key: string;
        };
        BiomedicalEligibilityRevisionCatalogValue: {
            /** @constant */
            state: "known";
            value: components["schemas"]["BiomedicalEligibilityRevision"];
        };
        BiomedicalEligibilitySubjectEvidence: {
            jcr_category: string;
            /** Format: uuid */
            journal_subject_metric_id: string;
            metric_year: number;
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            subject_rule_id: string;
            subject_slug: components["schemas"]["TaxonomySlug"];
            /** Format: uuid */
            subject_version_id: string;
            /** Format: uuid */
            venue_id: string;
            /** Format: uuid */
            venue_metric_snapshot_id: string;
        };
        BiomedicalEligibilityVenueEvidence: components["schemas"]["BiomedicalEligibilityVenueEvidenceWithISSNL"] | components["schemas"]["BiomedicalEligibilityVenueEvidenceWithISSN"] | components["schemas"]["BiomedicalEligibilityVenueEvidenceWithEISSN"];
        BiomedicalEligibilityVenueEvidenceWithEISSN: {
            eissn: string;
            issn?: string;
            issn_l?: string;
            /** Format: uuid */
            venue_id: string;
        };
        BiomedicalEligibilityVenueEvidenceWithISSN: {
            eissn?: string;
            issn: string;
            issn_l?: string;
            /** Format: uuid */
            venue_id: string;
        };
        BiomedicalEligibilityVenueEvidenceWithISSNL: {
            eissn?: string;
            issn?: string;
            issn_l: string;
            /** Format: uuid */
            venue_id: string;
        };
        BooleanCatalogValue: {
            /** @constant */
            state: "known";
            value: boolean;
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        /** @enum {string} */
        CatalogValueState: "known" | "unknown" | "missing";
        CitationAnalysisEvidence: {
            /** Format: uuid */
            analysis_run_id: string;
            /** Format: date-time */
            as_of: string;
            formula_version: string;
            /** Format: date-time */
            generated_at: string;
            percentile: components["schemas"]["CitationPercentileEvidence"];
            source: string;
            source_revision: string;
            velocity: components["schemas"]["CitationVelocityEvidence"];
        };
        CitationAnalysisEvidenceCatalogValue: {
            /** @constant */
            state: "known";
            value: components["schemas"]["CitationAnalysisEvidence"];
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        CitationMomentumCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["CitationMomentumItem"][];
        };
        CitationMomentumItem: {
            citation_delta: components["schemas"]["IntegerCatalogValue"];
            citations_per_day: components["schemas"]["NumberCatalogValue"];
            cohort_percentile: components["schemas"]["RatioCatalogValue"];
            paper: components["schemas"]["PaperSummary"];
        };
        CitationPercentileCatalogValue: {
            /** @constant */
            state: "known";
            value: number;
        } | components["schemas"]["InsufficientEvidenceCatalogValue"] | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        CitationPercentileEvidence: components["schemas"]["CitationPercentileKnownEvidence"] | components["schemas"]["CitationPercentileInsufficientEvidence"];
        CitationPercentileInsufficientEvidence: {
            /** Format: uuid */
            citation_snapshot_id: string;
            cohort_key: string;
            cohort_size: number;
            minimum_cohort_size: number;
            /** Format: uuid */
            publication_type_id: string;
            publication_year: number;
            reason: string;
            /** @constant */
            state: "insufficient_evidence";
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            subject_version_id: string;
            supporting_work_ids: string[];
        };
        CitationPercentileKnownEvidence: {
            /** Format: uuid */
            citation_snapshot_id: string;
            cohort_key: string;
            cohort_size: number;
            midrank: number;
            minimum_cohort_size: number;
            /** Format: uuid */
            publication_type_id: string;
            publication_year: number;
            /** @constant */
            state: "known";
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            subject_version_id: string;
            supporting_work_ids: string[];
        };
        CitationSnapshot: {
            count: number;
            coverage: number;
            dataset_version: string;
            definition_version: string;
            /** Format: uuid */
            ingestion_job_id: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            retrieved_at: string;
            source: string;
            /** Format: uuid */
            source_record_id: string;
        };
        CitationSnapshotsCatalogValue: {
            /** @constant */
            state: "known";
            value: components["schemas"]["CitationSnapshot"][];
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        CitationVelocityCatalogValue: {
            /** @constant */
            state: "known";
            value: number;
        } | components["schemas"]["InsufficientEvidenceCatalogValue"] | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        CitationVelocityEvidence: components["schemas"]["CitationVelocityKnownEvidence"] | components["schemas"]["CitationVelocityInsufficientEvidence"];
        CitationVelocityInsufficientEvidence: {
            missing: string[];
            reason: string;
            /** @constant */
            state: "insufficient_evidence";
            window_days: number;
        };
        CitationVelocityKnownEvidence: {
            /** Format: uuid */
            baseline_snapshot_id: string;
            /** Format: uuid */
            current_snapshot_id: string;
            elapsed_days: number;
            /** @constant */
            state: "known";
            window_days: number;
        };
        ConfidenceInterval: {
            lower: number;
            upper: number;
        };
        CurationCatalogValue: {
            /** @constant */
            state: "known";
            value: components["schemas"]["CurationPayload"];
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        CurationPayload: {
            /** Format: date-time */
            assessed_at: string;
            /** @enum {string} */
            decision: "accepted" | "rejected" | "not_applicable";
            evidence: unknown;
            matched_rules: unknown;
            metric_year: number;
            policy_name: string;
            policy_version: number;
        };
        DateTimeCatalogValue: {
            /** @constant */
            state: "known";
            /** Format: date-time */
            value: string;
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        DiscoveryResponse: {
            /** @constant */
            api_version: "v1";
            /** @constant */
            health: "/health";
            /** @constant */
            service: "medpaperhub-api";
            /** @constant */
            status: "ok";
        };
        DistributionBucket: {
            count: components["schemas"]["IntegerCatalogValue"];
            label: string;
            ratio: components["schemas"]["RatioCatalogValue"];
        };
        DistributionCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["DistributionBucket"][];
        };
        EditorialPatternCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["EditorialPatternEstimate"][];
        };
        EditorialPatternEstimate: {
            adjusted_p_value: components["schemas"]["NumberCatalogValue"];
            baseline: string;
            confidence_interval: components["schemas"]["ConfidenceInterval"];
            coverage_ratio: components["schemas"]["RatioCatalogValue"];
            dimension: string;
            estimate: components["schemas"]["NumberCatalogValue"];
            /** @enum {string} */
            estimate_kind: "odds_ratio" | "rate_ratio";
            field_baseline_count: components["schemas"]["IntegerCatalogValue"];
            /** @constant */
            interpretation_kind: "editorial_pattern";
            label: string;
            minimum_support_count: components["schemas"]["IntegerCatalogValue"];
            p_value: components["schemas"]["NumberCatalogValue"];
            support_papers: components["schemas"]["IntegerCatalogValue"];
        };
        EntityMomentumCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["EntityMomentumItem"][];
        };
        EntityMomentumItem: {
            adjusted_p_value: components["schemas"]["NumberCatalogValue"];
            baseline_count: components["schemas"]["IntegerCatalogValue"];
            confidence_interval: components["schemas"]["ConfidenceInterval"];
            /** @enum {string} */
            entity_type: "disease" | "method" | "publication_type" | "study_design" | "target";
            estimate: components["schemas"]["NumberCatalogValue"];
            independent_journal_count: components["schemas"]["IntegerCatalogValue"];
            independent_team_count: components["schemas"]["IntegerCatalogValue"];
            label: string;
            model_family: string;
            p_value: components["schemas"]["NumberCatalogValue"];
            recent_count: components["schemas"]["IntegerCatalogValue"];
        };
        FacetBucket: {
            count: number;
            key: string;
            label: string;
        };
        Facets: {
            methods: components["schemas"]["FacetBucket"][];
            paper_types: components["schemas"]["FacetBucket"][];
            sources: components["schemas"]["FacetBucket"][];
            statuses: components["schemas"]["FacetBucket"][];
            topics: components["schemas"]["FacetBucket"][];
        };
        HealthResponse: {
            /** @constant */
            service: "medpaperhub-api";
            /** @constant */
            status: "ok";
        };
        HomeCoverage: {
            analysis: components["schemas"]["AnalysisMetadata"];
            citation_coverage_ratio: components["schemas"]["RatioCatalogValue"];
            jcr_metric_year: number;
            mesh_coverage_ratio: components["schemas"]["RatioCatalogValue"];
            publication_type_coverage_ratio: components["schemas"]["RatioCatalogValue"];
            taxonomy_version: string;
        };
        HomeResponse: {
            active_journals: components["schemas"]["JournalActivityCollection"];
            catalog_generation: string;
            citation_momentum: components["schemas"]["CitationMomentumCollection"];
            coverage: components["schemas"]["HomeCoverage"];
            entity_momentum: components["schemas"]["EntityMomentumCollection"];
            evidence_gaps: string[];
            /** Format: date-time */
            generated_at: string;
            latest_papers: components["schemas"]["PaperAnalysisCollection"];
            research_opportunities: components["schemas"]["ResearchOpportunityAnalysisCollection"];
            scope: {
                jcr_metric_year: number;
                taxonomy_version: string;
            };
            subject_momentum: components["schemas"]["SubjectTrendCollection"];
        };
        InsufficientEvidenceCatalogValue: {
            reason: string;
            /** @constant */
            state: "insufficient_evidence";
        };
        IntegerCatalogValue: {
            /** @constant */
            state: "known";
            value: number;
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        JournalActivityCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["JournalActivityItem"][];
        };
        JournalActivityItem: {
            journal: components["schemas"]["JournalSummary"];
            paper_count: components["schemas"]["IntegerCatalogValue"];
            publication_change_ratio: components["schemas"]["NumberCatalogValue"];
        };
        JournalCuration: {
            /** Format: date-time */
            assessed_at: string;
            /** @constant */
            decision: "accepted";
            evidence: components["schemas"]["JournalCurationEvidenceItem"][];
            matched_rules: string[];
            metric_year: number;
            policy_name: string;
            policy_version: number;
        };
        JournalCurationEvidenceItem: {
            label: string;
            value: string;
        };
        JournalDetailResponse: {
            aliases?: string[];
            categories?: components["schemas"]["JournalMetricCategory"][];
            curation: components["schemas"]["JournalCuration"];
            editorial_patterns: components["schemas"]["EditorialPatternCollection"];
            eissn?: components["schemas"]["StringCatalogValue"];
            evidence_gaps: string[];
            /** Format: uuid */
            id: string;
            issn_l?: components["schemas"]["StringCatalogValue"];
            issns?: string[];
            jcr_metric_year: number;
            jif: components["schemas"]["NumberCatalogValue"];
            paper_count?: components["schemas"]["IntegerCatalogValue"];
            publisher?: components["schemas"]["StringCatalogValue"];
            recent_papers: components["schemas"]["RecentPaperCollection"];
            slug: components["schemas"]["TaxonomySlug"];
            taxonomy_version: string;
            title: string;
        };
        JournalListResponse: {
            analysis: components["schemas"]["AnalysisMetadata"];
            catalog_generation: string;
            items: components["schemas"]["JournalSummary"][];
            jcr_metric_year: number;
            pagination: components["schemas"]["Pagination"];
            taxonomy_version: string;
        };
        JournalMetricCategory: {
            name: string;
            quartile: string;
        };
        JournalReference: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["TaxonomySlug"];
            title: string;
        };
        JournalSummary: {
            aliases?: string[];
            categories?: components["schemas"]["JournalMetricCategory"][];
            eissn?: components["schemas"]["StringCatalogValue"];
            /** Format: uuid */
            id: string;
            issn_l?: components["schemas"]["StringCatalogValue"];
            issns?: string[];
            jcr_metric_year: number;
            jif: components["schemas"]["NumberCatalogValue"];
            paper_count?: components["schemas"]["IntegerCatalogValue"];
            publisher?: components["schemas"]["StringCatalogValue"];
            slug: components["schemas"]["TaxonomySlug"];
            taxonomy_version?: string;
            title: string;
        };
        MeshHeading: {
            descriptor_ui: string;
            is_major_topic: boolean;
            label: string;
            qualifiers: components["schemas"]["MeshQualifier"][];
            source_path: string;
        };
        MeshHeadingsCatalogValue: {
            /** @constant */
            state: "known";
            value: components["schemas"]["MeshHeading"][];
        } | components["schemas"]["MissingCatalogValue"];
        MeshQualifier: {
            is_major_topic: boolean;
            label: string;
            qualifier_ui: string;
            source_path: string;
        };
        Method: components["schemas"]["TaxonomyItem"];
        MethodListResponse: {
            items: components["schemas"]["Method"][];
            pagination: components["schemas"]["Pagination"];
        };
        MissingCatalogValue: {
            /** @constant */
            state: "missing";
        };
        MissingSignal: {
            affected_entity_ids?: string[];
            reason?: string;
            signal: string;
        };
        NumberCatalogValue: {
            /** @constant */
            state: "known";
            value: number;
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        Pagination: {
            has_more: boolean;
            limit: number;
            /** @description Signed opaque cursor for the next page, or null at the end. */
            next_cursor: string | null;
            total: number;
        };
        PaperAnalysisCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["PaperSummary"][];
        };
        PaperDetail: {
            abstract?: components["schemas"]["StringCatalogValue"];
            abstract_snippet?: components["schemas"]["StringCatalogValue"];
            article_usage: components["schemas"]["MissingCatalogValue"];
            authors?: components["schemas"]["AuthorReference"][];
            canonical_key?: string;
            citation_analysis_evidence?: components["schemas"]["CitationAnalysisEvidenceCatalogValue"];
            citation_count?: components["schemas"]["IntegerCatalogValue"];
            citation_percentile: components["schemas"]["CitationPercentileCatalogValue"];
            citation_snapshots: components["schemas"]["CitationSnapshotsCatalogValue"];
            citation_source: components["schemas"]["StringCatalogValue"];
            citation_velocity: components["schemas"]["CitationVelocityCatalogValue"];
            curation?: components["schemas"]["CurationCatalogValue"];
            has_benchmark: components["schemas"]["BooleanCatalogValue"];
            has_code: components["schemas"]["BooleanCatalogValue"];
            has_data: components["schemas"]["BooleanCatalogValue"];
            /** Format: uuid */
            id: string;
            jcr_assessment: components["schemas"]["BiomedicalEligibilityRevisionCatalogValue"];
            journal?: components["schemas"]["JournalReference"];
            mesh_headings: components["schemas"]["MeshHeadingsCatalogValue"];
            methods?: components["schemas"]["TaxonomyReference"][];
            open_fulltext: components["schemas"]["MissingCatalogValue"];
            publication_types?: string[];
            publication_types_state: components["schemas"]["PublicationTypesCatalogValue"];
            published_at: components["schemas"]["DateTimeCatalogValue"];
            source_provenance?: components["schemas"]["SourceProvenanceCatalogValue"];
            status: components["schemas"]["PaperStatus"];
            subjects?: components["schemas"]["TaxonomyReference"][];
            title: string;
            topics?: components["schemas"]["TaxonomyReference"][];
            trend_score?: components["schemas"]["NumberCatalogValue"];
            type: components["schemas"]["PaperTypeCatalogValue"];
        };
        PaperListResponse: {
            facets: components["schemas"]["Facets"];
            items: components["schemas"]["PaperSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @enum {string} */
        PaperStatus: "active" | "withdrawn" | "retracted" | "rejected" | "superseded";
        PaperSummary: {
            abstract?: components["schemas"]["StringCatalogValue"];
            abstract_snippet?: components["schemas"]["StringCatalogValue"];
            article_usage: components["schemas"]["MissingCatalogValue"];
            authors?: components["schemas"]["AuthorReference"][];
            canonical_key?: string;
            citation_analysis_evidence?: components["schemas"]["CitationAnalysisEvidenceCatalogValue"];
            citation_count?: components["schemas"]["IntegerCatalogValue"];
            citation_percentile: components["schemas"]["CitationPercentileCatalogValue"];
            citation_snapshots: components["schemas"]["CitationSnapshotsCatalogValue"];
            citation_source: components["schemas"]["StringCatalogValue"];
            citation_velocity: components["schemas"]["CitationVelocityCatalogValue"];
            curation?: components["schemas"]["CurationCatalogValue"];
            has_benchmark: components["schemas"]["BooleanCatalogValue"];
            has_code: components["schemas"]["BooleanCatalogValue"];
            has_data: components["schemas"]["BooleanCatalogValue"];
            /** Format: uuid */
            id: string;
            jcr_assessment: components["schemas"]["BiomedicalEligibilityRevisionCatalogValue"];
            journal?: components["schemas"]["JournalReference"];
            mesh_headings: components["schemas"]["MeshHeadingsCatalogValue"];
            methods?: components["schemas"]["TaxonomyReference"][];
            open_fulltext: components["schemas"]["MissingCatalogValue"];
            publication_types?: string[];
            publication_types_state: components["schemas"]["PublicationTypesCatalogValue"];
            published_at: components["schemas"]["DateTimeCatalogValue"];
            source_provenance?: components["schemas"]["SourceProvenanceCatalogValue"];
            status: components["schemas"]["PaperStatus"];
            subjects?: components["schemas"]["TaxonomyReference"][];
            title: string;
            topics?: components["schemas"]["TaxonomyReference"][];
            trend_score?: components["schemas"]["NumberCatalogValue"];
            type: components["schemas"]["PaperTypeCatalogValue"];
        };
        /** @enum {string} */
        PaperType: "research_article" | "review" | "preprint" | "dataset" | "benchmark";
        PaperTypeCatalogValue: {
            /** @constant */
            state: "known";
            value: components["schemas"]["PaperType"];
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        ProblemDetails: {
            /** @enum {string} */
            code: "invalid_request_id" | "route_not_found" | "method_not_allowed" | "catalog_not_published" | "resource_not_found" | "invalid_cursor" | "cursor_context_mismatch" | "validation_error" | "internal_error";
            detail: string;
            /** Format: uri-reference */
            instance: string;
            request_id: components["schemas"]["RequestID"];
            status: number;
            title: string;
            /** Format: uri-reference */
            type: string;
        };
        PublicationTypesCatalogValue: {
            /** @constant */
            state: "known";
            value: string[];
        } | components["schemas"]["MissingCatalogValue"];
        RankingMetadata: {
            confidence?: components["schemas"]["RatioCatalogValue"];
            coverage?: components["schemas"]["RatioCatalogValue"];
            formula_version?: string;
            /** Format: date-time */
            generated_at?: string;
            missing_signals: (string | components["schemas"]["MissingSignal"])[];
            window_days?: number;
        };
        RatioCatalogValue: {
            /** @constant */
            state: "known";
            value: number;
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        RecentPaperCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["PaperSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        RequestID: string;
        ResearchOpportunity: {
            /** Format: uuid */
            analysis_run_id: string;
            coverage_ratio: components["schemas"]["RatioCatalogValue"];
            estimates: components["schemas"]["ResearchOpportunityEstimate"][];
            formula_version: string;
            /** Format: date-time */
            generated_at: string;
            /** Format: uuid */
            id: string;
            limitations?: string[];
            missing_signals?: string[];
            recommended_next_steps?: string[];
            status: components["schemas"]["ResearchOpportunityStatus"];
            summary?: string;
            supporting_work_ids: string[];
            target_id: string;
            target_kind: string;
            title: string;
            trigger_rule: components["schemas"]["ResearchOpportunityTriggerRule"];
        };
        ResearchOpportunityAnalysisCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["ResearchOpportunity"][];
        };
        ResearchOpportunityEstimate: {
            confidence_interval: components["schemas"]["ConfidenceInterval"];
            metric: string;
            value: number;
        };
        ResearchOpportunityListResponse: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["ResearchOpportunity"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @enum {string} */
        ResearchOpportunityStatus: "worth_pursuing" | "proceed_with_caution" | "not_recommended_now" | "insufficient_evidence";
        ResearchOpportunityTriggerRule: {
            code: string;
            version: string;
        };
        /** @enum {string} */
        SourceName: "crossref" | "arxiv" | "openreview" | "s2" | "pubmed" | "pmc" | "openalex" | "springer_nature" | "elsevier" | "manual";
        SourceProvenance: {
            event_key: string;
            normalization_policy_version: string;
            projection_policy_version: string;
            scope_policy_version: string;
            source: string;
            /** Format: uuid */
            source_record_id: string;
            /** Format: date-time */
            source_time: string;
        };
        SourceProvenanceCatalogValue: {
            /** @constant */
            state: "known";
            value: components["schemas"]["SourceProvenance"][];
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        StatsResponse: {
            formula_version: string;
            /** Format: date-time */
            generated_at: string;
            methods_total: components["schemas"]["IntegerCatalogValue"];
            papers_last_7_days: components["schemas"]["IntegerCatalogValue"];
            papers_total: components["schemas"]["IntegerCatalogValue"];
            topics_total: components["schemas"]["IntegerCatalogValue"];
            with_benchmark_ratio: components["schemas"]["RatioCatalogValue"];
            with_code_ratio: components["schemas"]["RatioCatalogValue"];
            with_data_ratio: components["schemas"]["RatioCatalogValue"];
        };
        StringArrayCatalogValue: {
            /** @constant */
            state: "known";
            value: string[];
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        StringCatalogValue: {
            /** @constant */
            state: "known";
            value: string;
        } | components["schemas"]["UnknownCatalogValue"] | components["schemas"]["MissingCatalogValue"];
        SubjectDetailResponse: {
            active_journals: components["schemas"]["JournalActivityCollection"];
            description: components["schemas"]["StringCatalogValue"];
            evidence_gaps: string[];
            /** Format: uuid */
            id: string;
            jcr_metric_year: number;
            journal_count: components["schemas"]["IntegerCatalogValue"];
            mesh_distribution: components["schemas"]["DistributionCollection"];
            name: string;
            paper_count: components["schemas"]["IntegerCatalogValue"];
            publication_type_distribution: components["schemas"]["DistributionCollection"];
            recent_papers: components["schemas"]["RecentPaperCollection"];
            slug: components["schemas"]["TaxonomySlug"];
            taxonomy_version: string;
            trend_estimates: components["schemas"]["SubjectTrendCollection"];
        };
        SubjectListResponse: {
            analysis: components["schemas"]["AnalysisMetadata"];
            catalog_generation: string;
            items: components["schemas"]["SubjectSummary"][];
            jcr_metric_year: number;
            pagination: components["schemas"]["Pagination"];
            taxonomy_version: string;
        };
        SubjectSummary: {
            description: components["schemas"]["StringCatalogValue"];
            /** Format: uuid */
            id: string;
            jcr_metric_year: number;
            journal_count: components["schemas"]["IntegerCatalogValue"];
            name: string;
            paper_count: components["schemas"]["IntegerCatalogValue"];
            slug: components["schemas"]["TaxonomySlug"];
            taxonomy_version: string;
        };
        SubjectTrendCollection: {
            analysis: components["schemas"]["AnalysisMetadata"];
            items: components["schemas"]["SubjectTrendEstimate"][];
        };
        SubjectTrendEstimate: {
            adjusted_p_value: components["schemas"]["NumberCatalogValue"];
            baseline_count: components["schemas"]["IntegerCatalogValue"];
            confidence_interval: components["schemas"]["ConfidenceInterval"];
            estimate: components["schemas"]["NumberCatalogValue"];
            independent_journal_count: components["schemas"]["IntegerCatalogValue"];
            independent_team_count: components["schemas"]["IntegerCatalogValue"];
            label?: string;
            model_family: string;
            p_value: components["schemas"]["NumberCatalogValue"];
            recent_count: components["schemas"]["IntegerCatalogValue"];
            subject?: components["schemas"]["TaxonomyReference"];
        };
        TaxonomyItem: {
            description: components["schemas"]["StringCatalogValue"];
            /** Format: uuid */
            id: string;
            name: string;
            paper_count: number;
            paper_ids?: string[];
            slug: components["schemas"]["TaxonomySlug"];
        };
        TaxonomyReference: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: components["schemas"]["TaxonomySlug"];
        };
        TaxonomySlug: string;
        Topic: components["schemas"]["TaxonomyItem"];
        TopicListResponse: {
            items: components["schemas"]["Topic"][];
            pagination: components["schemas"]["Pagination"];
        };
        TrendItem: {
            method?: components["schemas"]["Method"];
            paper?: components["schemas"]["PaperSummary"];
            rank: number;
            rank_change?: number;
            ranking: components["schemas"]["RankingMetadata"];
            score: number;
            /** Format: uuid */
            subject_id: string;
            topic?: components["schemas"]["Topic"];
        };
        TrendListResponse: {
            /** Format: date-time */
            generated_at: string;
            items: components["schemas"]["TrendItem"][];
            pagination: components["schemas"]["Pagination"];
            window_days: number;
        };
        UnknownCatalogValue: {
            /** @constant */
            state: "unknown";
        };
    };
    responses: {
        /** @description Complete Home document from the current biomedical generation. */
        BiomedicalHomeOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HomeResponse"];
            };
        };
        /** @description Accepted biomedical Journals from the current generation. */
        BiomedicalJournalListOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["JournalListResponse"];
            };
        };
        /** @description One accepted biomedical Journal with paginated recent papers. */
        BiomedicalJournalOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["JournalDetailResponse"];
            };
        };
        /** @description Accepted biomedical Subjects from the current generation. */
        BiomedicalSubjectListOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SubjectListResponse"];
            };
        };
        /** @description One accepted biomedical Subject with paginated recent papers. */
        BiomedicalSubjectOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SubjectDetailResponse"];
            };
        };
        /** @description No catalog generation has been published. */
        CatalogUnavailableProblem: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The cursor belongs to different filters, sort, window, or generation. */
        CursorConflictProblem: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The API process is healthy. This does not imply a catalog is published. */
        HealthOK: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HealthResponse"];
            };
        };
        /** @description The server could not complete the request. */
        InternalProblem: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description X-Request-ID was present but invalid. */
        InvalidRequestIDProblem: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Methods from the current catalog generation. */
        MethodListOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MethodListResponse"];
            };
        };
        /** @description The known route only supports GET. */
        MethodNotAllowedProblem: {
            headers: {
                Allow: components["headers"]["AllowGET"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description One visible method. */
        MethodOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Method"];
            };
        };
        /** @description Persisted method trend rows for the selected window. */
        MethodTrendsOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TrendListResponse"];
            };
        };
        /** @description The resource is absent or not visible in the current generation. */
        NotFoundProblem: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description One visible paper. */
        PaperDetailOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PaperDetail"];
            };
        };
        /** @description Matching visible papers. */
        PaperListOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PaperListResponse"];
            };
        };
        /** @description Persisted paper trend rows for the selected window. */
        PaperTrendsOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TrendListResponse"];
            };
        };
        /** @description Persisted research opportunities from the current generation. */
        ResearchOpportunitiesOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ResearchOpportunityListResponse"];
            };
        };
        /** @description The requested /api route is not registered. */
        RouteNotFoundProblem: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Statistics from the current catalog generation. */
        StatsOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StatsResponse"];
            };
        };
        /** @description Topics from the current catalog generation. */
        TopicListOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TopicListResponse"];
            };
        };
        /** @description One visible topic. */
        TopicOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Topic"];
            };
        };
        /** @description Persisted topic trend rows for the selected window. */
        TopicTrendsOK: {
            headers: {
                "X-Catalog-Generation": components["headers"]["XCatalogGeneration"];
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TrendListResponse"];
            };
        };
        /** @description Query validation failed or a cursor was malformed or had an invalid signature. */
        ValidationProblem: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Signed opaque cursor, at most 2048 bytes. */
        Cursor: string;
        HasBenchmark: boolean;
        HasCode: boolean;
        HasData: boolean;
        Limit: number;
        MethodFilter: components["schemas"]["TaxonomySlug"];
        OpportunityStatus: components["schemas"]["ResearchOpportunityStatus"];
        /** @description Paper UUID. Invalid UUID text is deliberately reported as resource_not_found. */
        PaperID: string;
        /** @description Trimmed full-text query. Relevance sort requires this parameter. */
        PaperQuery: string;
        PaperSort: "relevance" | "published_at_desc" | "citations_desc" | "trend_desc";
        PaperStatus: components["schemas"]["PaperStatus"];
        PaperType: components["schemas"]["PaperType"];
        /** @description Inclusive RFC3339Nano lower bound. */
        PublishedFrom: string;
        /** @description Inclusive RFC3339Nano upper bound. */
        PublishedTo: string;
        /** @description Optional correlation ID matching the service's strict character set. */
        RequestID: components["schemas"]["RequestID"];
        /** @description Stable lowercase taxonomy slug. */
        Slug: components["schemas"]["TaxonomySlug"];
        Source: components["schemas"]["SourceName"];
        TopicFilter: components["schemas"]["TaxonomySlug"];
        TrendWindowDays: number;
    };
    requestBodies: never;
    headers: {
        /** @description The only method supported by the requested route. */
        AllowGET: "GET";
        /** @description UUID of the immutable catalog generation used for the response. */
        XCatalogGeneration: string;
        /** @description Request correlation identifier generated or reused by the service. */
        XRequestID: components["schemas"]["RequestID"];
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDiscovery: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable discovery metadata for the public API. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getBiomedicalHome: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BiomedicalHomeOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listBiomedicalJournals: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BiomedicalJournalListOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getBiomedicalJournal: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path: {
                /** @description Stable lowercase taxonomy slug. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BiomedicalJournalOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            404: components["responses"]["NotFoundProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listMethods: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MethodListOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getMethod: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path: {
                /** @description Stable lowercase taxonomy slug. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MethodOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            404: components["responses"]["NotFoundProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listPapers: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                has_benchmark?: components["parameters"]["HasBenchmark"];
                has_code?: components["parameters"]["HasCode"];
                has_data?: components["parameters"]["HasData"];
                limit?: components["parameters"]["Limit"];
                method?: components["parameters"]["MethodFilter"];
                /** @description Inclusive RFC3339Nano lower bound. */
                published_from?: components["parameters"]["PublishedFrom"];
                /** @description Inclusive RFC3339Nano upper bound. */
                published_to?: components["parameters"]["PublishedTo"];
                /** @description Trimmed full-text query. Relevance sort requires this parameter. */
                q?: components["parameters"]["PaperQuery"];
                sort?: components["parameters"]["PaperSort"];
                source?: components["parameters"]["Source"];
                status?: components["parameters"]["PaperStatus"];
                topic?: components["parameters"]["TopicFilter"];
                type?: components["parameters"]["PaperType"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaperListOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getPaper: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path: {
                /** @description Paper UUID. Invalid UUID text is deliberately reported as resource_not_found. */
                id: components["parameters"]["PaperID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaperDetailOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            404: components["responses"]["NotFoundProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listResearchOpportunities: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                status?: components["parameters"]["OpportunityStatus"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ResearchOpportunitiesOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatsOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listBiomedicalSubjects: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BiomedicalSubjectListOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getBiomedicalSubject: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path: {
                /** @description Stable lowercase taxonomy slug. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BiomedicalSubjectOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            404: components["responses"]["NotFoundProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listTopics: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TopicListOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getTopic: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path: {
                /** @description Stable lowercase taxonomy slug. */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TopicOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            404: components["responses"]["NotFoundProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listMethodTrends: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                window_days?: components["parameters"]["TrendWindowDays"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MethodTrendsOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listPaperTrends: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                window_days?: components["parameters"]["TrendWindowDays"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaperTrendsOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    listTopicTrends: {
        parameters: {
            query?: {
                /** @description Signed opaque cursor, at most 2048 bytes. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                window_days?: components["parameters"]["TrendWindowDays"];
            };
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TopicTrendsOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            409: components["responses"]["CursorConflictProblem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["CatalogUnavailableProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional correlation ID matching the service's strict character set. */
                "X-Request-ID"?: components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HealthOK"];
            400: components["responses"]["InvalidRequestIDProblem"];
            405: components["responses"]["MethodNotAllowedProblem"];
            default: components["responses"]["InternalProblem"];
        };
    };
}
